const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Json,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Behaviors.lunarray_LiteTween.Acts.SetTarget,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.TiledBg.Cnds.IsOnLayer,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Exps.Opacity,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.JavaScriptInEvents.Menu_Event77_Act1,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.JavaScriptInEvents.SaveGame_Event1_Act1,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.int
	];
};
self.C3_JsPropNameTable = [
	{LiteTween: 0},
	{LiteTween2: 0},
	{Group: 0},
	{Group2: 0},
	{Sine: 0},
	{Sine2: 0},
	{logo: 0},
	{bg_color_base: 0},
	{bg_batik: 0},
	{bg_white: 0},
	{x_target: 0},
	{y_target: 0},
	{Vector: 0},
	{x_target_1: 0},
	{y_target_1: 0},
	{x_target_2: 0},
	{y_target_2: 0},
	{Ellipse: 0},
	{ScrollTo: 0},
	{camera: 0},
	{state: 0},
	{x_start: 0},
	{y_start: 0},
	{menu_state: 0},
	{scale: 0},
	{buttons: 0},
	{Touch: 0},
	{Keyboard: 0},
	{black: 0},
	{btn_keyboard: 0},
	{cancelKeybpard: 0},
	{Text: 0},
	{alert: 0},
	{authResponse: 0},
	{bg_color_belajar: 0},
	{state_frame: 0},
	{pelajari_huruf_judul: 0},
	{frame: 0},
	{indicator: 0},
	{modal: 0},
	{isLoggedIn: 0},
	{MENU_STATE: 0},
	{CAMERA_STATE: 0},
	{isMusic: 0},
	{LOGIN_STATE: 0},
	{USERNAME: 0},
	{SUPABASE_ID: 0},
	{SUPABASE_USERNAME: 0},
	{SUPABASE_SUCCESS: 0},
	{pelajari_huruf_frame: 0},
	{modalOpened: 0}
];

self.InstanceType = {
	Group: class extends self.ISpriteInstance {},
	Group2: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	bg_color_base: class extends self.ITiledBackgroundInstance {},
	bg_batik: class extends self.ITiledBackgroundInstance {},
	bg_white: class extends self.ITiledBackgroundInstance {},
	Vector: class extends self.ISpriteInstance {},
	Ellipse: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	black: class extends self.ITiledBackgroundInstance {},
	btn_keyboard: class extends self.ISpriteInstance {},
	cancelKeybpard: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	alert: class extends self.ISpriteInstance {},
	authResponse: class extends self.IJSONInstance {},
	bg_color_belajar: class extends self.ITiledBackgroundInstance {},
	pelajari_huruf_judul: class extends self.ISpriteInstance {},
	indicator: class extends self.ISpriteInstance {},
	modal: class extends self.ISpriteInstance {}
}